/** @type {import('next').NextConfig} */
const nextConfig = {
  env: {
    POKESEARCH_FIREBASE_API_KEY: process.env.POKESEARCH_FIREBASE_API_KEY,
    POKESEARCH_FIREBASE_AUTH_DOMAIN:
      process.env.POKESEARCH_FIREBASE_AUTH_DOMAIN,
    POKESEARCH_FIREBASE_PROJECT_ID: process.env.POKESEARCH_FIREBASE_PROJECT_ID,
    POKESEARCH_FIREBASE_STORAGE_BUCKET:
      process.env.POKESEARCH_FIREBASE_STORAGE_BUCKET,
    POKESEARCH_FIREBASE_MESSAGING_SENDER_ID:
      process.env.POKESEARCH_FIREBASE_MESSAGING_SENDER_ID,
    POKESEARCH_FIREBASE_APP_ID: process.env.POKESEARCH_FIREBASE_APP_ID,
  },
};

module.exports = nextConfig;
