version: "3.9"
services:
  db:
    image: postgres
    ports:
      - "3306:3306"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: "Asia/Tokyo"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  app:
    build:
      context: ./backend
      dockerfile: ./../infra/rails/Dockerfile
    image: poke-rails
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./backend/:/backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
volumes:
  postgres_volume:
